title: open samen
subtitle: organisatie van open samenwerkingen in publieke digitale transformatie
img: /open-samen.png
url: https://www.opensamen.nl
keywords: open samenwerking, publieke sector, overheid, digitale transformatie, innovatie
twitter_user: "@jpagroenen"
quote: If you want to go fast, go alone. If you want to go far, go together.
description: Losjes gecoördineerde samenwerkingen aan innovatieve publieke digitale ​​producten en diensten die open beschikbaar worden gesteld aan zowel bijdragers als niet-bijdragers.

collections:
  samenwerkingen:
    output: true
    permalink: /samenwerking/:name/

defaults:
  - scope:
      type: samenwerkingen
    values:
      layout: samenwerking
      collection: samenwerkingen