title: open samen
subtitle: open samenwerkingen in publieke digitale transformatie
img: /open-samen.png
icon: /open-samen-icon.png
url: https://www.opensamen.nl
keywords: open samenwerking, publieke sector, overheid, digitale transformatie, innovatie
twitter_user: "@jpagroenen"
quote: If you want to go fast, go alone. If you want to go far, go together.
description: Bottom-up samenwerken aan publieke digitale producten en diensten.

collections:
  samenwerkingen:
    output: true
    permalink: /samenwerking/:name/

defaults:
  - scope:
      type: samenwerkingen
    values:
      layout: samenwerking
      collection: samenwerkingen